services:
- docker
script:
- make
- ls -la | grep pdf
deploy:
  provider: releases
  api_key:
    secure: UPe5VtT1gvmVDiXjN0IpGQ2Chj7tyjE0+jZrOBWMi1lM6mvCypp1fZ6WyNnTS5ADPAcsDhNuX9QQbhcSoBXUOfv0B/OR2AeDMO4L/eXtExombHVsz2mtzIcn0uAN3JryOyQ7Gf3IZSaCNTpCPQY4AEqHtWy7pXtE4wQlS9jw0kSmvA29FscaG4mgqyW5SifthHGLAssRsCSimTI1U525FlHUmlTFyvoUewdN2lyNCFMFtr9Y46A+SNCdV+9Id9hlqM4zfz1yvMtYxymg5gZcqi/BBm/1Cg+OSRJDoz1TNyX2/c77iZzIH2ZGPymypoEErAiKfZW/EJlZ8Rt1pBdIUu1S4xVXLyRgiyAdR3Q2ZkIcviI4fiYFforJKmxwU1VodqdQm8yuTmJStVZrbGn+fJ6HLuawB3XgfOrFpv1ad0+wYjVqmFsbXVWp7rFAGecW5wpUHARzk+MMcOmJin3u+4GKEkH1ubR662c4glAmn8rgKoVlQq/30iErUiVZRTJdyLG50E5m39ytn1sT/HATHPvIUBhKvE7koVREVKPJRY5ENqizfH42SUVoYL33XZym+wRxHGqMtWT43sGlfGFxja4ZbRyfsi+byAndPriv/a1g260rPxFRtrTK6WfckymDlAJyDEKI5WwQqdyFLMpdsFuJdCSaZtiAeMD1/16qVRE=
  file: seminar.pdf
  skip_cleanup: true
  on:
    repo: uniba-ktr/SemiTeX
    tags: true
